inherit_from:
 - .rubocop_todo.yml
 - .rubocop_cocoapods.yml

#- Xcodeproj ------------------------------------------------------------------

AllCops:
  Exclude:
    - spec/fixtures/**/*
    - lib/cocoapods-core/vendor/**/*

FileName:
  Exclude:
    - lib/cocoapods-core.rb
