#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_FRAMEWORK_COREFOUNDATION 1
#define HAVE_COREFOUNDATION_COREFOUNDATION_H 1
#define HAVE_COREFOUNDATION_CFSTREAM_H 1
#define HAVE_COREFOUNDATION_CFPROPERTYLIST_H 1
#define HAVE_RUBY_ST_H 1
#endif
