name: Lint
on:
  push:
    branches:
      - "master"
      - "*-stable"
  pull_request:
    branches:
      - master
      - "*-stable"

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6]
        os: [ubuntu-24.04]

    name: Lint
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set build image var
        run: echo "ImageVersion=$ImageVersion"  >> $GITHUB_ENV

      - name: Checkout git
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run Tests
        run: bundle exec rake spec:all
        env:
          COCOAPODS_CI_TASKS: LINT
